// HelpFlow AI — Implementation Contract v1.2: Socket.IO contract.
// Transport rule: state-changing commands (handoff, accept, takeover, reassign, release, close) go through
// REST so they get RBAC guards, 409 semantics and simple tests. Socket.IO carries message sends (with ack)
// and server push. Missed events are recovered with REST: GET .../messages?afterSeq=<lastSeq>.
// Typing indicators and presence broadcasts are intentionally NOT part of the MVP.

import type { ApiError } from "./api-errors";

// ─────────────────────────── Shared DTOs ───────────────────────────

export type ConversationStatus = "AI_ACTIVE" | "WAITING_AGENT" | "AGENT_ACTIVE" | "CLOSED";
export type CloseReason = "CLOSED_BY_AGENT" | "AGENT_UNAVAILABLE" | "INACTIVITY";
export type MessageSenderType = "CUSTOMER" | "AI" | "AGENT" | "SYSTEM";
export type MessageStreamStatus = "COMPLETED" | "FAILED" | "INTERRUPTED";

export interface Citation {
  index: number; // [1], [2] ... as rendered in the answer
  chunkId: string; // must belong to the retrieval set sent to the model
  documentId: string;
  documentName: string;
  pageNumber: number | null;
}

export interface MessageDto {
  id: string;
  conversationId: string;
  seq: string; // BigInt serialized as a decimal string — compare with BigInt(seq), never Number
  clientMessageId: string | null;
  senderType: MessageSenderType;
  senderId: string | null;
  content: string;
  streamStatus: MessageStreamStatus | null;
  citations: Citation[] | null;
  insufficientKnowledge?: boolean; // AI messages only
  createdAt: string; // ISO-8601
}

export interface ConversationDto {
  id: string;
  chatbotId: string;
  customerId: string;
  status: ConversationStatus;
  assignedAgentId: string | null;
  handoffRequestedAt: string | null;
  closedAt: string | null;
  closeReason: CloseReason | null;
  lastMessageAt: string;
}

/** Every client→server event with a reply uses this ack shape. Errors reuse REST error codes. */
export type AckResult<T> = { ok: true; data: T } | { ok: false; error: ApiError };
export type Ack<T> = (result: AckResult<T>) => void;

// ─────────────────────── Namespace: /widget (customer) ───────────────────────
// Handshake: io("/widget", { auth: { visitorToken } }). Server verifies the signed token, loads the
// customer and auto-joins room conversation:{id} for the customer's open conversation (if any).

export interface WidgetSendMessagePayload {
  clientMessageId: string; // UUID generated by the widget; retries reuse it
  content: string; // 1..DEFAULTS.socket.maxMessageChars
}

export interface WidgetSendMessageResult {
  message: MessageDto; // the persisted customer message (existing row on duplicate send)
  conversation: ConversationDto; // lazily created on the first message
}

export interface WidgetClientToServerEvents {
  "message:send": (payload: WidgetSendMessagePayload, ack: Ack<WidgetSendMessageResult>) => void;
}

// ─────────────────────── Namespace: /agent (dashboard) ───────────────────────
// Handshake: io("/agent", { auth: { accessToken, organizationId } }). Server verifies JWT + active
// membership, then joins org:{organizationId}:inbox and user:{userId}. An expired token disconnects
// with error TOKEN_EXPIRED; the client refreshes via REST and reconnects.

export interface AgentJoinPayload {
  conversationId: string;
}

export interface AgentSendMessagePayload {
  conversationId: string;
  clientMessageId: string;
  content: string;
}

export interface AgentClientToServerEvents {
  /** Watch a conversation (read-only for anyone except the assigned agent). */
  "conversation:join": (payload: AgentJoinPayload, ack: Ack<ConversationDto>) => void;
  "conversation:leave": (payload: AgentJoinPayload) => void;
  /** Allowed only when status = AGENT_ACTIVE and assignedAgentId = current user. */
  "message:send": (payload: AgentSendMessagePayload, ack: Ack<MessageDto>) => void;
}

// ─────────────────────────── Server → client (both namespaces) ───────────────────────────
// Rooms: conversation:{id} (customer + watching agents), org:{orgId}:inbox (agents), user:{userId}.

export interface AiStartedPayload {
  conversationId: string;
  streamId: string; // becomes the persisted message id
}

export interface AiChunkPayload {
  conversationId: string;
  streamId: string;
  index: number; // 0-based, strictly increasing; clients drop duplicates / out-of-order chunks
  delta: string;
}

export interface AiCompletedPayload {
  conversationId: string;
  message: MessageDto; // final persisted row: seq, citations, streamStatus = COMPLETED
}

export interface AiFailedPayload {
  conversationId: string;
  streamId: string;
  message: MessageDto | null; // persisted partial answer (FAILED / INTERRUPTED) or null if nothing streamed
  error: ApiError;
}

export interface InboxUpdatedPayload {
  conversation: ConversationDto; // pushed to org:{orgId}:inbox on every status/assignment change
}

export interface ServerToClientEvents {
  "message:created": (message: MessageDto) => void; // customer, agent and SYSTEM messages
  "ai:started": (payload: AiStartedPayload) => void;
  "ai:chunk": (payload: AiChunkPayload) => void;
  "ai:completed": (payload: AiCompletedPayload) => void;
  "ai:failed": (payload: AiFailedPayload) => void;
  "conversation:updated": (conversation: ConversationDto) => void; // to conversation:{id}
  "inbox:updated": (payload: InboxUpdatedPayload) => void; // /agent only
}

export interface SocketData {
  organizationId: string;
  userId?: string; // /agent
  customerId?: string; // /widget
  chatbotId?: string; // /widget
  requestId: string;
}
